### ISSUE TITLE
[Feature Request] Show PKGBUILD in same window as package details

### ISSUE THREAD

**Issue by ajgringo619** [moson-mo/pacseek#12]
Love the direction this package is going - thanks a bunch for the hard work!

I tried the **Show PKGBUILD** feature today; like it, but I'd like an option to not shell out, but show it right below the package info.

**Comment by moson-mo** [comment]
Hi @ajgringo619 

Thanks for your feedback.
Is there any specific reason (besides cosmetics) to display it within the pacseek UI?

The reason for displaying it outside of the UI is because of space + letting people open it with their favorite editor, to have syntax highlighting, etc. (or if you want to save it and "do something" with it later).
(Might only be me, but my terminal windows tend to be sized a quarter of the whole screen)

Now, what I could imagine though is to display it instead/on-top of the package info (rather than below it). So when you press CTRL+P (or click "Show PKGBUILD") it would occupy the whole right hand side of the screen. 
-> But only if I can make it to have to have syntax highlighting and scrolling.

**Comment by ajgringo619** [comment]
This is a purely cosmetic request; I've never had the need to modify a PKGBUILD, so I didn't even consider using an external editor. I tend to use maximized terminal windows with multiple tabs, so space isn't an issue.

Occupying the whole subwindow, like a toggle, would be fine.

**Comment by moson-mo** [comment]
Internal displaying of PKGBUILD is implemented with [v1.5.0 ](https://github.com/moson-mo/pacseek/releases/tag/v1.5.0) 
It can be enabled in the settings ("Show PKGBUILD internally")

![image](https://user-images.githubusercontent.com/13588013/183618760-4a4d2c7e-0995-4e55-98f7-ff3af2cca75a.png)
