### ISSUE TITLE
[Feature request] IgnorePkg and IgnoreGroup

### ISSUE THREAD

**Issue by Mudskipper875** [moson-mo/pacseek#18]
Packages and groups can be blacklisted from updating the `IgnorePkg` and `IgnoreGroup` options in `pacman.conf`.

It may be better if these packages are hidden from the upgradable packages list when running `pacseek -u`. (The default sysupgrade command `yay` doesn't install these packages anyway)

**Comment by moson-mo** [comment]
I guess one could argue both ways:

I mean, usually you'd use IgnorePkg to temporarily block an upgrade, like for example if there is some bug in version 1.2.3 of a program.
Now you'd probably still want to be notified if there is an upgrade available. Maybe the bug got fixed in 1.2.4. Showing these updates would probably remind you of trying the new version and eventually removing it from IgnorePkg.

What I can think of as a good compromise is to visualize an ignored package on the upgrades screen.

f.e. something like this:

![image](https://user-images.githubusercontent.com/13588013/189490932-ba784ac5-f812-4fde-b0a1-f3c0455275e5.png)

Does that make sense?

**Comment by Mudskipper875** [comment]
Yes marking them as ignored or changing the text color is a better idea 👍.

And also how about placing the ignored packages list below the sysupgrade button?

**Comment by moson-mo** [comment]
This looks pretty decent I think:

![image](https://user-images.githubusercontent.com/13588013/189496142-b5ce41ae-18f9-4c6e-b8d2-9f1def6ba3f5.png)

Ignored packages will be placed at the bottom of the list.

**Comment by Mudskipper875** [comment]
Looks good 👍
