### ISSUE TITLE
[REQUEST] Allow to leave upgrade command array empty

### ISSUE THREAD

**Issue by manfred3000** [moson-mo/pacseek#2]
Thanks for this little tool!

I'm using `pacseek` with `paru` to retrieve `PKGBUILD`s via `paru -G` as install command and don't want to update my system everytime. Leaving the upgrade array empty results in `pacseek` filling it back in with `yay -Syu`.
As a workaround I've entered `pacman -Q pacman >/dev/null 2>&1` as a "dummy".

No biggie, but would be nice to be able to just leave that array empty :)

**Comment by moson-mo** [comment]
Hi @manfred3000 

Thanks for the feedback.

I see. Actually that is due to some upgrade function that is checking if the config already contains a certain option (some options got added with newer versions) and to make sure the default value is being applied if not...

Now the upgrade command is only run when you specifically execute it with CTRL+U.
If you do not use that functionality at all, you can put whatever you want into the upgrade command.

Maybe just put `paru` or simply a whitespace.

**Comment by manfred3000** [comment]
Thanks for the clarification!
